export function SrcManager(){
    let src =  {
        color: {
         0: [
             ('./planet/tileFront/normal/0_front_normal_image.png'),
             ('./planet/tileFront/normal/1_front_normal_image.png'),
             ('./planet/tileFront/normal/2_front_normal_image.png'),
             ('./planet/tileFront/normal/3_front_normal_image.png'),
             ('./planet/tileFront/normal/4_front_normal_image.png'),
             ('./planet/tileFront/normal/5_front_normal_image.png'),
             ('./planet/tileFront/normal/6_front_normal_image.png'),
             ('./planet/tileFront/normal/7_front_normal_image.png'),
             ('./planet/tileFront/normal/8_front_normal_image.png'),
             ('./planet/tileFront/normal/9_front_normal_image.png'),
             ('./planet/tileFront/normal/10_front_normal_image.png'),
             ('./planet/tileFront/normal/11_front_normal_image.png'),
             ('./planet/tileFront/normal/12_front_normal_image.png'),
             ('./planet/tileFront/normal/13_front_normal_image.png'),
             ('./planet/tileFront/normal/14_front_normal_image.png'),
             ('./planet/tileFront/normal/15_front_normal_image.png'),
           ],
 
           1: [
             ('./planet/tileFront/normal/0_front_normal_image.png'),
             ('./planet/tileFront/normal/1_front_normal_image.png'),
             ('./planet/tileFront/normal/2_front_normal_image.png'),
             ('./planet/tileFront/normal/3_front_normal_image.png'),
             ('./planet/tileFront/normal/4_front_normal_image.png'),
             ('./planet/tileFront/normal/5_front_normal_image.png'),
             ('./planet/tileFront/normal/6_front_normal_image.png'),
             ('./planet/tileFront/normal/7_front_normal_image.png'),
             ('./planet/tileFront/normal/8_front_normal_image.png'),
             ('./planet/tileFront/normal/9_front_normal_image.png'),
             ('./planet/tileFront/normal/10_front_normal_image.png'),
             ('./planet/tileFront/normal/11_front_normal_image.png'),
             ('./planet/tileFront/normal/12_front_normal_image.png'),
             ('./planet/tileFront/normal/13_front_normal_image.png'),
             ('./planet/tileFront/normal/14_front_normal_image.png'),
             ('./planet/tileFront/normal/15_front_normal_image.png'),
           ],
 
           2: [
             ('./planet/tileFront/normal/0_front_normal_image.png'),
             ('./planet/tileFront/normal/1_front_normal_image.png'),
             ('./planet/tileFront/normal/2_front_normal_image.png'),
             ('./planet/tileFront/normal/3_front_normal_image.png'),
             ('./planet/tileFront/normal/4_front_normal_image.png'),
             ('./planet/tileFront/normal/5_front_normal_image.png'),
             ('./planet/tileFront/normal/6_front_normal_image.png'),
             ('./planet/tileFront/normal/7_front_normal_image.png'),
             ('./planet/tileFront/normal/8_front_normal_image.png'),
             ('./planet/tileFront/normal/9_front_normal_image.png'),
             ('./planet/tileFront/normal/10_front_normal_image.png'),
             ('./planet/tileFront/normal/11_front_normal_image.png'),
             ('./planet/tileFront/normal/12_front_normal_image.png'),
             ('./planet/tileFront/normal/13_front_normal_image.png'),
             ('./planet/tileFront/normal/14_front_normal_image.png'),
             ('./planet/tileFront/normal/15_front_normal_image.png'),
           ]
 
        },
        displacement:{
         0: [
             ('./planet/tileFront/normal/0_front_normal_image.png'),
             ('./planet/tileFront/normal/1_front_normal_image.png'),
             ('./planet/tileFront/normal/2_front_normal_image.png'),
             ('./planet/tileFront/normal/3_front_normal_image.png'),
             ('./planet/tileFront/normal/4_front_normal_image.png'),
             ('./planet/tileFront/normal/5_front_normal_image.png'),
             ('./planet/tileFront/normal/6_front_normal_image.png'),
             ('./planet/tileFront/normal/7_front_normal_image.png'),
             ('./planet/tileFront/normal/8_front_normal_image.png'),
             ('./planet/tileFront/normal/9_front_normal_image.png'),
             ('./planet/tileFront/normal/10_front_normal_image.png'),
             ('./planet/tileFront/normal/11_front_normal_image.png'),
             ('./planet/tileFront/normal/12_front_normal_image.png'),
             ('./planet/tileFront/normal/13_front_normal_image.png'),
             ('./planet/tileFront/normal/14_front_normal_image.png'),
             ('./planet/tileFront/normal/15_front_normal_image.png'),
           ],
 
           1: [
             ('./planet/tileFront/normal/0_front_normal_image.png'),
             ('./planet/tileFront/normal/1_front_normal_image.png'),
             ('./planet/tileFront/normal/2_front_normal_image.png'),
             ('./planet/tileFront/normal/3_front_normal_image.png'),
             ('./planet/tileFront/normal/4_front_normal_image.png'),
             ('./planet/tileFront/normal/5_front_normal_image.png'),
             ('./planet/tileFront/normal/6_front_normal_image.png'),
             ('./planet/tileFront/normal/7_front_normal_image.png'),
             ('./planet/tileFront/normal/8_front_normal_image.png'),
             ('./planet/tileFront/normal/9_front_normal_image.png'),
             ('./planet/tileFront/normal/10_front_normal_image.png'),
             ('./planet/tileFront/normal/11_front_normal_image.png'),
             ('./planet/tileFront/normal/12_front_normal_image.png'),
             ('./planet/tileFront/normal/13_front_normal_image.png'),
             ('./planet/tileFront/normal/14_front_normal_image.png'),
             ('./planet/tileFront/normal/15_front_normal_image.png'),
           ],
 
           2: [
             ('./planet/tileFront/normal/0_front_normal_image.png'),
             ('./planet/tileFront/normal/1_front_normal_image.png'),
             ('./planet/tileFront/normal/2_front_normal_image.png'),
             ('./planet/tileFront/normal/3_front_normal_image.png'),
             ('./planet/tileFront/normal/4_front_normal_image.png'),
             ('./planet/tileFront/normal/5_front_normal_image.png'),
             ('./planet/tileFront/normal/6_front_normal_image.png'),
             ('./planet/tileFront/normal/7_front_normal_image.png'),
             ('./planet/tileFront/normal/8_front_normal_image.png'),
             ('./planet/tileFront/normal/9_front_normal_image.png'),
             ('./planet/tileFront/normal/10_front_normal_image.png'),
             ('./planet/tileFront/normal/11_front_normal_image.png'),
             ('./planet/tileFront/normal/12_front_normal_image.png'),
             ('./planet/tileFront/normal/13_front_normal_image.png'),
             ('./planet/tileFront/normal/14_front_normal_image.png'),
             ('./planet/tileFront/normal/15_front_normal_image.png'),
           ]
        }    
     }
 return src
 }